<a href="https://colab.research.google.com/github/morateng/2023_Data_Campus/blob/main/2)%EC%A3%BC%EC%9A%94_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC02_pandas_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas

In [1]:
import pandas as pd

### Series

### Series 생성
- #### Series() 함수

In [4]:
s1 = pd.Series([1, 2, 3])
type(s1)
s1

0    1
1    2
2    3
dtype: int64

- #### ndarray 이용

In [5]:
import numpy as np

s2 = pd.Series(np.arange(200))
s2

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int64

- #### data 와 index 함께 생성

In [6]:
s1 = pd.Series([1, 2, 3], [100, 200, 300])
s1

100    1
200    2
300    3
dtype: int64

In [7]:
fruit = pd.Series([2500, 3800, 1200], index=['apple', 'banana', 'lemon'])
print(fruit)

apple     2500
banana    3800
lemon     1200
dtype: int64


In [8]:
fruit.index

Index(['apple', 'banana', 'lemon'], dtype='object')

In [9]:
fruit.values

array([2500, 3800, 1200])

In [10]:
fruit['apple']

2500

In [11]:
fruit['apple'] = 1500
fruit

apple     1500
banana    3800
lemon     1200
dtype: int64

- ### Series 분석

In [12]:
s = pd.Series([1, 0, 3, 1, 0 ,2, 5, 4, 3, np.NaN])
s

0    1.0
1    0.0
2    3.0
3    1.0
4    0.0
5    2.0
6    5.0
7    4.0
8    3.0
9    NaN
dtype: float64

In [13]:
s.size

10

- #### size

In [14]:
s.size

10

- #### shape

In [16]:
s.shape

(10,)

- #### unique() 함수

In [17]:
s.unique()

array([ 1.,  0.,  3.,  2.,  5.,  4., nan])

- #### count() 함수

In [18]:
s.count()

9

- #### mean() 함수

In [19]:
s.mean()

2.111111111111111

- #### value_counts() 함수

In [20]:
s.value_counts()

1.0    2
0.0    2
3.0    2
2.0    1
5.0    1
4.0    1
dtype: int64

- #### head(), tail() 함수

In [21]:
s.head()

0    1.0
1    0.0
2    3.0
3    1.0
4    0.0
dtype: float64

In [22]:
s.tail()

5    2.0
6    5.0
7    4.0
8    3.0
9    NaN
dtype: float64

## Series 연산

- #### index 기준으로 연산

In [23]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'x'])
s2 = pd.Series([9, 6, 3, 2, 1], ['d','c', 'b', 'a', 'y'])
print(s1)
print(s2)

a    1
b    2
c    3
d    4
x    5
dtype: int64
d    9
c    6
b    3
a    2
y    1
dtype: int64


In [24]:
s1 * 2

a     2
b     4
c     6
d     8
x    10
dtype: int64

In [25]:
s1 + s2

a     3.0
b     5.0
c     9.0
d    13.0
x     NaN
y     NaN
dtype: float64

In [26]:
s1 * s2

a     2.0
b     6.0
c    18.0
d    36.0
x     NaN
y     NaN
dtype: float64

In [27]:
s1 ** s2

a         1.0
b         8.0
c       729.0
d    262144.0
x         NaN
y         NaN
dtype: float64

- #### 논리값을 이용한 Series 인덱싱

In [29]:
s = pd.Series([1, 0, 3, 1, 0, 2, 5, 4, 3, np.NaN])
s

0    1.0
1    0.0
2    3.0
3    1.0
4    0.0
5    2.0
6    5.0
7    4.0
8    3.0
9    NaN
dtype: float64

In [31]:
s > 3

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8    False
9    False
dtype: bool

In [32]:
s[s > 3]

6    5.0
7    4.0
dtype: float64

In [33]:
s[s % 2 == 0]

1    0.0
4    0.0
5    2.0
7    4.0
dtype: float64

In [34]:
s.index > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [35]:
s[s.index > 5]

6    5.0
7    4.0
8    3.0
9    NaN
dtype: float64

In [36]:
s[(s > 3) & (s <5)]

7    4.0
dtype: float64

In [37]:
(s >= 3).sum()

4

In [38]:
(s[s>=3]).sum()

15.0

### Series 변경과 슬라이싱

In [40]:
s = pd.Series(np.arange(10, 20, 2), ['a', 'b', 'c', 'd', 'e'])
s

a    10
b    12
c    14
d    16
e    18
dtype: int64

- #### 데이터 변경
    - #### index, drop() 함수 이용

In [41]:
s['a'] = 20
s

a    20
b    12
c    14
d    16
e    18
dtype: int64

In [42]:
s['x'] = 30
s

a    20
b    12
c    14
d    16
e    18
x    30
dtype: int64

In [44]:
s[['a', 'b']] = [100, 100]
s

a    100
b    100
c     14
d     16
e     18
x     30
dtype: int64

In [45]:
s.drop('a')

b    100
c     14
d     16
e     18
x     30
dtype: int64

- #### 슬라이싱

In [47]:
s[1:3]

b    100
c     14
dtype: int64

In [48]:
s['c':'d']

c    14
d    16
dtype: int64