### PCA
#### iris

- from sklearn.decomposition import PCA

In [1]:
import pandas as pd
import numpy as np

from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [4]:
x = iris.data[:,[0,2]]
y = iris.target

In [5]:
print(x.shape, y.shape)

(150, 2) (150,)


In [9]:
feature_name = [iris.feature_names[0], iris.feature_names[2]]
x_data = pd.DataFrame(x, columns=feature_name)
x_data.head()

sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5
4                5.0                1.4

In [10]:
y_data = pd.DataFrame(y, columns = ['target'])
y_data.head()

target
0       0
1       0
2       0
3       0
4       0

In [11]:
from sklearn.decomposition import PCA

In [12]:
pca = PCA(n_components=2)
pca.fit(x_data)

PCA(n_components=2)

In [13]:
pca.explained_variance_

array([3.66189877, 0.1400726 ])

In [14]:
pca.components_

array([[ 0.39360585,  0.9192793 ],
       [-0.9192793 ,  0.39360585]])

In [15]:
PCscore = pca.transform(x_data)
PCscore[0:5]

array([[-2.46024094, -0.24479165],
       [-2.53896211, -0.06093579],
       [-2.70961121,  0.08355948],
       [-2.56511594,  0.25420858],
       [-2.49960153, -0.15286372]])

In [16]:
x_data[0:5]

sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5
4                5.0                1.4

In [17]:
eigens_v = pca.components_.transpose()
print(eigens_v)

[[ 0.39360585 -0.9192793 ]
 [ 0.9192793   0.39360585]]


In [21]:
mX = np.matrix(x)
for i in range(x.shape[1]):
    mX[:,i] = mX[:,i]-np.mean(x[:,i])
mX_df= pd.DataFrame(mX)

In [22]:
(mX*eigens_v)[0:5]

matrix([[-2.46024094, -0.24479165],
        [-2.53896211, -0.06093579],
        [-2.70961121,  0.08355948],
        [-2.56511594,  0.25420858],
        [-2.49960153, -0.15286372]])

######## [참고] 혹시 PCA 축을 그릴 때 에러가 발생하면 origin 부분을 아래처럼 바꿔주세요.

- plt.quiver(*origin     -->      plt.quiver((0,0),(0,0)  

- #### 회귀분석

- from sklearn.linear_model import LogisticRegression
- from sklearn.metrics import confusion_matrix